template:
  name: "Product Team"
  description: "Product-focused development with design and QA"
  version: "1.0.0"
  tags:
    - "product"
    - "design"
    - "user-centered"

  variables:
    - name: "company_name"
      description: "Name of your company"
      default: "Product Co"
    - name: "budget"
      description: "Monthly budget in USD"
      var_type: "float"
      default: 80.0

  company:
    type: "product_team"
    budget_monthly: {{ budget | default(80.0) }}
    autonomy: 0.5

  departments:
    - name: "product"
      budget_percent: 30
      head_role: "Product Manager"
    - name: "engineering"
      budget_percent: 50
      head_role: "Backend Developer"
    - name: "quality_assurance"
      budget_percent: 20
      head_role: "QA Engineer"

  agents:
    - role: "Product Manager"
      level: "senior"
      model: "sonnet"
      personality_preset: "visionary_leader"
      department: "product"
    - role: "UX Designer"
      level: "mid"
      model: "sonnet"
      department: "product"
    - role: "Full-Stack Developer"
      level: "senior"
      model: "sonnet"
      personality_preset: "pragmatic_builder"
      department: "engineering"
    - role: "QA Engineer"
      level: "mid"
      model: "haiku"
      personality_preset: "methodical_analyst"
      department: "quality_assurance"

  workflow: "agile_kanban"
  communication: "hybrid"
