"""Communication subsystem for the AI company framework."""

from ai_company.communication.bus_memory import InMemoryMessageBus
from ai_company.communication.bus_protocol import MessageBus
from ai_company.communication.channel import Channel
from ai_company.communication.config import (
    CircuitBreakerConfig,
    CommunicationConfig,
    HierarchyConfig,
    LoopPreventionConfig,
    MeetingsConfig,
    MeetingTypeConfig,
    MessageBusConfig,
    MessageRetentionConfig,
    RateLimitConfig,
)
from ai_company.communication.conflict_resolution import (
    Conflict,
    ConflictPosition,
    ConflictResolution,
    ConflictResolutionConfig,
    ConflictResolutionOutcome,
    ConflictResolutionService,
    ConflictResolver,
    DebateConfig,
    DissentRecord,
    HybridConfig,
    JudgeEvaluator,
)
from ai_company.communication.conflict_resolution.authority_strategy import (
    AuthorityResolver,
)
from ai_company.communication.conflict_resolution.debate_strategy import (
    DebateResolver,
)
from ai_company.communication.conflict_resolution.human_strategy import (
    HumanEscalationResolver,
)
from ai_company.communication.conflict_resolution.hybrid_strategy import (
    HybridResolver,
)
from ai_company.communication.delegation import (
    AuthorityCheckResult,
    AuthorityValidator,
    DelegationRecord,
    DelegationRequest,
    DelegationResult,
    DelegationService,
    HierarchyResolver,
)
from ai_company.communication.dispatcher import DispatchResult, MessageDispatcher
from ai_company.communication.enums import (
    AttachmentType,
    ChannelType,
    CommunicationPattern,
    ConflictResolutionStrategy,
    ConflictType,
    MessageBusBackend,
    MessagePriority,
    MessageType,
)
from ai_company.communication.errors import (
    ChannelAlreadyExistsError,
    ChannelNotFoundError,
    CommunicationError,
    ConflictHierarchyError,
    ConflictResolutionError,
    ConflictStrategyError,
    DelegationAncestryError,
    DelegationAuthorityError,
    DelegationCircuitOpenError,
    DelegationDepthError,
    DelegationDuplicateError,
    DelegationError,
    DelegationLoopError,
    DelegationRateLimitError,
    HierarchyResolutionError,
    MessageBusAlreadyRunningError,
    MessageBusNotRunningError,
    NotSubscribedError,
)
from ai_company.communication.handler import (
    FunctionHandler,
    HandlerRegistration,
    MessageHandler,
    MessageHandlerFunc,
)
from ai_company.communication.loop_prevention import (
    CircuitBreakerState,
    DelegationCircuitBreaker,
    DelegationDeduplicator,
    DelegationGuard,
    DelegationRateLimiter,
    GuardCheckOutcome,
    check_ancestry,
    check_delegation_depth,
)
from ai_company.communication.message import Attachment, Message, MessageMetadata
from ai_company.communication.messenger import AgentMessenger
from ai_company.communication.subscription import DeliveryEnvelope, Subscription

__all__ = [
    "AgentMessenger",
    "Attachment",
    "AttachmentType",
    "AuthorityCheckResult",
    "AuthorityResolver",
    "AuthorityValidator",
    "Channel",
    "ChannelAlreadyExistsError",
    "ChannelNotFoundError",
    "ChannelType",
    "CircuitBreakerConfig",
    "CircuitBreakerState",
    "CommunicationConfig",
    "CommunicationError",
    "CommunicationPattern",
    "Conflict",
    "ConflictHierarchyError",
    "ConflictPosition",
    "ConflictResolution",
    "ConflictResolutionConfig",
    "ConflictResolutionError",
    "ConflictResolutionOutcome",
    "ConflictResolutionService",
    "ConflictResolutionStrategy",
    "ConflictResolver",
    "ConflictStrategyError",
    "ConflictType",
    "DebateConfig",
    "DebateResolver",
    "DelegationAncestryError",
    "DelegationAuthorityError",
    "DelegationCircuitBreaker",
    "DelegationCircuitOpenError",
    "DelegationDeduplicator",
    "DelegationDepthError",
    "DelegationDuplicateError",
    "DelegationError",
    "DelegationGuard",
    "DelegationLoopError",
    "DelegationRateLimiter",
    "DelegationRecord",
    "DelegationRequest",
    "DelegationResult",
    "DelegationService",
    "DeliveryEnvelope",
    "DispatchResult",
    "DissentRecord",
    "FunctionHandler",
    "GuardCheckOutcome",
    "HandlerRegistration",
    "HierarchyConfig",
    "HierarchyResolutionError",
    "HierarchyResolver",
    "HumanEscalationResolver",
    "HybridConfig",
    "HybridResolver",
    "InMemoryMessageBus",
    "JudgeEvaluator",
    "LoopPreventionConfig",
    "MeetingTypeConfig",
    "MeetingsConfig",
    "Message",
    "MessageBus",
    "MessageBusAlreadyRunningError",
    "MessageBusBackend",
    "MessageBusConfig",
    "MessageBusNotRunningError",
    "MessageDispatcher",
    "MessageHandler",
    "MessageHandlerFunc",
    "MessageMetadata",
    "MessagePriority",
    "MessageRetentionConfig",
    "MessageType",
    "NotSubscribedError",
    "RateLimitConfig",
    "Subscription",
    "check_ancestry",
    "check_delegation_depth",
]
