"""Assert the OpenAPI export is healthy and deterministic.

The ``docs/openapi/openapi.json`` artifact is regenerated by CI on every
docs deploy (see ``.github/workflows/pages.yml``) and is not committed.
This check guards against the ``SYNTHORG_DB_PATH``-unset regression that
caused audit #79 to report 107 missing endpoints: if a future change
removes the ``setdefault`` in ``export_openapi.py`` or breaks wiring so
controllers silently skip registration, the export still succeeds but
the schema is partial.  We catch that here by asserting a minimum path
count and a canary set of endpoints that must always be present.

Invoked from the ``openapi-liveness`` CI job (``.github/workflows/ci.yml``)
on every PR that touches Python sources, tests, scripts, or the export
itself.  Safe to run locally before pushing.
"""

import os
import sys
import traceback

# Match ``export_openapi.py``'s determinism contract so this check
# exercises the same wiring path CI uses for docs deploys.
os.environ.setdefault("SYNTHORG_DB_PATH", ":memory:")

MIN_PATH_COUNT = 200

# Canary endpoints the audit (2026-04-20) identified as missing when
# the determinism fix regresses.  Their presence proves the full
# integrations / OAuth / clients wiring fired.
CANARY_PATHS = frozenset(
    {
        "/api/v1/health",
        "/api/v1/agents",
        "/api/v1/clients",
        "/api/v1/workflows",
        "/api/v1/budget/config",
        "/api/v1/departments",
    }
)


def main() -> int:
    """Run the export in-memory and assert the schema looks healthy."""
    try:
        from synthorg.api.app import create_app
        from synthorg.api.openapi import inject_rfc9457_responses

        app = create_app()
        schema = inject_rfc9457_responses(app.openapi_schema.to_schema())
    except Exception as exc:
        print("OpenAPI export failed:", file=sys.stderr)
        traceback.print_exception(exc)
        return 1

    paths = schema.get("paths") or {}
    path_count = len(paths)

    errors: list[str] = []
    if path_count < MIN_PATH_COUNT:
        errors.append(
            f"Schema has {path_count} paths; expected at least {MIN_PATH_COUNT}. "
            "A controller wiring regression likely caused endpoints to skip "
            "registration.  Check `SYNTHORG_DB_PATH` handling in "
            "scripts/export_openapi.py.",
        )

    missing_canary = sorted(CANARY_PATHS - paths.keys())
    if missing_canary:
        errors.append(
            f"Canary endpoints missing from schema: {missing_canary}. "
            "Either the route was removed (update CANARY_PATHS) or wiring "
            "regressed (fix the underlying controller).",
        )

    if errors:
        print("OpenAPI liveness check failed:", file=sys.stderr)
        for line in errors:
            print(f"  - {line}", file=sys.stderr)
        return 1

    print(f"OpenAPI liveness OK: {path_count} paths, all canaries present.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
