name: Setup Python with uv
description: Install uv, Python, and project dependencies

inputs:
  python-version:
    description: Python version to install
    required: false
    default: "3.14"

runs:
  using: composite
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6.0.0
      with:
        enable-cache: true

    - name: Install Python
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: uv python install "$PYTHON_VERSION"

    - name: Install dependencies
      shell: bash
      env:
        PYTHON_VERSION: ${{ inputs.python-version }}
      run: uv sync --frozen --python "$PYTHON_VERSION"
